package(default_visibility = ["//visibility:public"]) 

exports_files([
	"shmem_transport.cc",
	"shmem_framer.cc",
	"shmem_queue.cc",
	"shmem_segment.cc",
	"shmem_channel.cc",
	"shmem_transport.h",
	"shmem_framer.h",
	"shmem_queue.h",
	"shmem_segment.h",
	"shmem_protocol.h",
	"shmem_memory.h",
])

