#!/usr/bin/env python3
"""Plot latency and ops/sec curves for transport performance sweeps.

Uses the unified CSV (transport_sweeps.csv) generated by
extract_benchmark_json_to_csv.py. Focuses on symmetric req=resp entries.

Outputs two PNGs (and optional SVGs):
  transport_latency.png / .svg   (median/mean per-iteration latency ~ cpu_time)
  transport_ops.png / .svg       (operations per second = 1e9 / cpu_time_ns)

Usage:
    python tools/plot_transport_latency_ops.py \
            --csv transport_sweeps.csv \
            [--latency-out transport_latency.png] [--ops-out transport_ops.png] \
            [--latency-svg latency.svg] [--ops-svg ops.svg] [--out-dir .perf_tmp]

Options:
    --include-zero  Include 0/0 size points (default omit)
    --all           Include metadata mutation variants (default only NoOpMutator + shmem)
    --out-dir DIR   Directory for output artifacts (default .perf_tmp) if explicit paths not provided

Notes:
  cpu_time_ns in the CSV (from Google Benchmark) is already the mean per-iteration
  time, so it directly represents unary round-trip latency for the ping-pong.
"""
from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

try:
    import matplotlib.pyplot as plt  # type: ignore
except ModuleNotFoundError as e:
    raise SystemExit("matplotlib is required. Install with: pip install matplotlib") from e


@dataclass
class Point:
    size: int
    latency_us: float
    ops_per_s: float


def load_points(csv_path: Path, include_zero: bool, include_all: bool) -> Dict[str, List[Point]]:
    per_transport: Dict[str, Dict[int, Point]] = {}
    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                transport = row.get("transport", "").strip()
                if not transport:
                    continue
                size_req = int(row.get("req_bytes", "0") or 0)
                size_resp = int(row.get("resp_bytes", "0") or 0)
                # Our CSV header is 'cpu_time_ns'; fall back to 'cpu_time' if needed.
                if "cpu_time_ns" in row and row["cpu_time_ns"]:
                    cpu_time_ns = float(row["cpu_time_ns"])
                elif "cpu_time" in row and row["cpu_time"]:
                    cpu_time_ns = float(row["cpu_time"])  # already in ns in this context
                else:
                    continue
            except ValueError:
                continue
            if size_req != size_resp:
                continue
            if size_req == 0 and not include_zero:
                continue
            name = row.get("bench_name", "")
            if not include_all and "NoOpMutator" not in name and "ShmemPromise" not in name:
                # allow shmem bench (contains ShmemPromise) and NoOpMutator variants
                continue
            if cpu_time_ns <= 0:
                continue
            latency_us = cpu_time_ns / 1000.0
            ops_per_s = 1e9 / cpu_time_ns
            existing = per_transport.setdefault(transport, {}).get(size_req)
            if existing is None or latency_us < existing.latency_us:
                per_transport[transport][size_req] = Point(size_req, latency_us, ops_per_s)
    return {t: [per_transport[t][s] for s in sorted(per_transport[t].keys())] for t in per_transport}


def plot(data: Dict[str, List[Point]], kind: str, out_png: Path, out_svg: Path | None) -> None:
    if not data:
        raise RuntimeError("No data to plot")
    color_map = {
        "inproc": "#1b9e77",
        "shmem": "#d95f02",
        "uds": "#7570b3",
    }
    plt.figure(figsize=(9, 6))
    for t, pts in sorted(data.items()):
        x = [p.size for p in pts]
        if kind == "latency":
            y = [p.latency_us for p in pts]
            ylabel = "Latency (µs per RPC)"
            title = "Unary Ping-Pong Latency by Transport"
        else:
            y = [p.ops_per_s for p in pts]
            ylabel = "Operations / Second"
            title = "Unary Ping-Pong Ops/sec by Transport"
        plt.plot(x, y, marker="o", linewidth=1.5, label=t, color=color_map.get(t))
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel("Payload size (bytes) [symmetric req=resp]")
    plt.ylabel(ylabel)
    plt.title(title + " (DEBUG build)")
    plt.grid(True, which="both", linestyle=":", linewidth=0.5)
    plt.legend()
    plt.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_png, dpi=160)
    if out_svg:
        plt.savefig(out_svg)
    expected = {"inproc", "shmem", "uds"}
    present = set(data.keys())
    missing = expected - present
    note = f" (missing: {','.join(sorted(missing))})" if missing else ""
    print(f"Wrote {out_png}" + (f" and {out_svg}" if out_svg else "") + note)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Plot latency and ops/sec curves for transports")
    ap.add_argument("--csv", default="transport_sweeps.csv", type=Path)
    ap.add_argument("--latency-out", type=Path, help="Explicit latency PNG path (else <out-dir>/transport_latency.png)")
    ap.add_argument("--ops-out", type=Path, help="Explicit ops PNG path (else <out-dir>/transport_ops.png)")
    ap.add_argument("--latency-svg", type=Path, default=None)
    ap.add_argument("--ops-svg", type=Path, default=None)
    ap.add_argument("--out-dir", type=Path, default=Path(".perf_tmp"), help="Directory for output artifacts")
    ap.add_argument("--include-zero", action="store_true")
    ap.add_argument("--all", action="store_true")
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    if not args.csv.exists():
        raise SystemExit(f"CSV not found: {args.csv}")
    # The CSV header used 'cpu_time_ns'; ensure that; if not present we will adapt.
    # Normalize header if necessary.
    # For current generated CSV, header includes 'cpu_time_ns'.
    data = load_points(args.csv, include_zero=args.include_zero, include_all=args.all)
    if not data:
        raise SystemExit("No matching data; try --all or --include-zero")
    latency_png = args.latency_out if args.latency_out else args.out_dir / "transport_latency.png"
    ops_png = args.ops_out if args.ops_out else args.out_dir / "transport_ops.png"
    latency_svg = args.latency_svg if args.latency_svg else (args.out_dir / "transport_latency.svg" if args.latency_out is None else None)
    ops_svg = args.ops_svg if args.ops_svg else (args.out_dir / "transport_ops.svg" if args.ops_out is None else None)
    latency_png.parent.mkdir(parents=True, exist_ok=True)
    plot(data, "latency", latency_png, latency_svg)
    plot(data, "ops", ops_png, ops_svg)
    return 0

if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
